server:
  port: 6854

spring:
  datasource:
    url: jdbc:mysql://10.1.20.85:3306/test01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    database: 1
    host: 10.1.20.85
    port: 6380
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


logging:
  config: classpath:logback-boot.xml

management:
  server:
    port: 9001
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always